// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/schema"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/tran"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tranMixin := schema.Tran{}.Mixin()
	tran.Policy = privacy.NewPolicies(tranMixin[0], schema.Tran{})
	tran.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := tran.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	tranMixinFields0 := tranMixin[0].Fields()
	_ = tranMixinFields0
	tranFields := schema.Tran{}.Fields()
	_ = tranFields
	// tranDescCreatedAt is the schema descriptor for created_at field.
	tranDescCreatedAt := tranMixinFields0[0].Descriptor()
	// tran.DefaultCreatedAt holds the default value on creation for the created_at field.
	tran.DefaultCreatedAt = tranDescCreatedAt.Default.(func() uint32)
	// tranDescUpdatedAt is the schema descriptor for updated_at field.
	tranDescUpdatedAt := tranMixinFields0[1].Descriptor()
	// tran.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tran.DefaultUpdatedAt = tranDescUpdatedAt.Default.(func() uint32)
	// tran.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tran.UpdateDefaultUpdatedAt = tranDescUpdatedAt.UpdateDefault.(func() uint32)
	// tranDescDeletedAt is the schema descriptor for deleted_at field.
	tranDescDeletedAt := tranMixinFields0[2].Descriptor()
	// tran.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	tran.DefaultDeletedAt = tranDescDeletedAt.Default.(func() uint32)
	// tranDescFromAccountID is the schema descriptor for from_account_id field.
	tranDescFromAccountID := tranFields[1].Descriptor()
	// tran.DefaultFromAccountID holds the default value on creation for the from_account_id field.
	tran.DefaultFromAccountID = tranDescFromAccountID.Default.(func() uuid.UUID)
	// tranDescToAccountID is the schema descriptor for to_account_id field.
	tranDescToAccountID := tranFields[2].Descriptor()
	// tran.DefaultToAccountID holds the default value on creation for the to_account_id field.
	tran.DefaultToAccountID = tranDescToAccountID.Default.(func() uuid.UUID)
	// tranDescAmount is the schema descriptor for amount field.
	tranDescAmount := tranFields[3].Descriptor()
	// tran.DefaultAmount holds the default value on creation for the amount field.
	tran.DefaultAmount = tranDescAmount.Default.(decimal.Decimal)
	// tranDescFeeAmount is the schema descriptor for fee_amount field.
	tranDescFeeAmount := tranFields[4].Descriptor()
	// tran.DefaultFeeAmount holds the default value on creation for the fee_amount field.
	tran.DefaultFeeAmount = tranDescFeeAmount.Default.(decimal.Decimal)
	// tranDescChainTxID is the schema descriptor for chain_tx_id field.
	tranDescChainTxID := tranFields[5].Descriptor()
	// tran.DefaultChainTxID holds the default value on creation for the chain_tx_id field.
	tran.DefaultChainTxID = tranDescChainTxID.Default.(string)
	// tranDescState is the schema descriptor for state field.
	tranDescState := tranFields[6].Descriptor()
	// tran.DefaultState holds the default value on creation for the state field.
	tran.DefaultState = tranDescState.Default.(string)
	// tranDescExtra is the schema descriptor for extra field.
	tranDescExtra := tranFields[7].Descriptor()
	// tran.DefaultExtra holds the default value on creation for the extra field.
	tran.DefaultExtra = tranDescExtra.Default.(string)
	// tranDescID is the schema descriptor for id field.
	tranDescID := tranFields[0].Descriptor()
	// tran.DefaultID holds the default value on creation for the id field.
	tran.DefaultID = tranDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.11.2" // Version of ent codegen.
)
