// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/appcoin"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/coinbase"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/coinextra"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/exchangerate"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/setting"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/tran"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppCoin is the client for interacting with the AppCoin builders.
	AppCoin *AppCoinClient
	// CoinBase is the client for interacting with the CoinBase builders.
	CoinBase *CoinBaseClient
	// CoinExtra is the client for interacting with the CoinExtra builders.
	CoinExtra *CoinExtraClient
	// ExchangeRate is the client for interacting with the ExchangeRate builders.
	ExchangeRate *ExchangeRateClient
	// Setting is the client for interacting with the Setting builders.
	Setting *SettingClient
	// Tran is the client for interacting with the Tran builders.
	Tran *TranClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppCoin = NewAppCoinClient(c.config)
	c.CoinBase = NewCoinBaseClient(c.config)
	c.CoinExtra = NewCoinExtraClient(c.config)
	c.ExchangeRate = NewExchangeRateClient(c.config)
	c.Setting = NewSettingClient(c.config)
	c.Tran = NewTranClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		AppCoin:      NewAppCoinClient(cfg),
		CoinBase:     NewCoinBaseClient(cfg),
		CoinExtra:    NewCoinExtraClient(cfg),
		ExchangeRate: NewExchangeRateClient(cfg),
		Setting:      NewSettingClient(cfg),
		Tran:         NewTranClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		AppCoin:      NewAppCoinClient(cfg),
		CoinBase:     NewCoinBaseClient(cfg),
		CoinExtra:    NewCoinExtraClient(cfg),
		ExchangeRate: NewExchangeRateClient(cfg),
		Setting:      NewSettingClient(cfg),
		Tran:         NewTranClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppCoin.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AppCoin.Use(hooks...)
	c.CoinBase.Use(hooks...)
	c.CoinExtra.Use(hooks...)
	c.ExchangeRate.Use(hooks...)
	c.Setting.Use(hooks...)
	c.Tran.Use(hooks...)
}

// AppCoinClient is a client for the AppCoin schema.
type AppCoinClient struct {
	config
}

// NewAppCoinClient returns a client for the AppCoin from the given config.
func NewAppCoinClient(c config) *AppCoinClient {
	return &AppCoinClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appcoin.Hooks(f(g(h())))`.
func (c *AppCoinClient) Use(hooks ...Hook) {
	c.hooks.AppCoin = append(c.hooks.AppCoin, hooks...)
}

// Create returns a builder for creating a AppCoin entity.
func (c *AppCoinClient) Create() *AppCoinCreate {
	mutation := newAppCoinMutation(c.config, OpCreate)
	return &AppCoinCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppCoin entities.
func (c *AppCoinClient) CreateBulk(builders ...*AppCoinCreate) *AppCoinCreateBulk {
	return &AppCoinCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppCoin.
func (c *AppCoinClient) Update() *AppCoinUpdate {
	mutation := newAppCoinMutation(c.config, OpUpdate)
	return &AppCoinUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppCoinClient) UpdateOne(ac *AppCoin) *AppCoinUpdateOne {
	mutation := newAppCoinMutation(c.config, OpUpdateOne, withAppCoin(ac))
	return &AppCoinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppCoinClient) UpdateOneID(id uuid.UUID) *AppCoinUpdateOne {
	mutation := newAppCoinMutation(c.config, OpUpdateOne, withAppCoinID(id))
	return &AppCoinUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppCoin.
func (c *AppCoinClient) Delete() *AppCoinDelete {
	mutation := newAppCoinMutation(c.config, OpDelete)
	return &AppCoinDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppCoinClient) DeleteOne(ac *AppCoin) *AppCoinDeleteOne {
	return c.DeleteOneID(ac.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AppCoinClient) DeleteOneID(id uuid.UUID) *AppCoinDeleteOne {
	builder := c.Delete().Where(appcoin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppCoinDeleteOne{builder}
}

// Query returns a query builder for AppCoin.
func (c *AppCoinClient) Query() *AppCoinQuery {
	return &AppCoinQuery{
		config: c.config,
	}
}

// Get returns a AppCoin entity by its id.
func (c *AppCoinClient) Get(ctx context.Context, id uuid.UUID) (*AppCoin, error) {
	return c.Query().Where(appcoin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppCoinClient) GetX(ctx context.Context, id uuid.UUID) *AppCoin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppCoinClient) Hooks() []Hook {
	hooks := c.hooks.AppCoin
	return append(hooks[:len(hooks):len(hooks)], appcoin.Hooks[:]...)
}

// CoinBaseClient is a client for the CoinBase schema.
type CoinBaseClient struct {
	config
}

// NewCoinBaseClient returns a client for the CoinBase from the given config.
func NewCoinBaseClient(c config) *CoinBaseClient {
	return &CoinBaseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coinbase.Hooks(f(g(h())))`.
func (c *CoinBaseClient) Use(hooks ...Hook) {
	c.hooks.CoinBase = append(c.hooks.CoinBase, hooks...)
}

// Create returns a builder for creating a CoinBase entity.
func (c *CoinBaseClient) Create() *CoinBaseCreate {
	mutation := newCoinBaseMutation(c.config, OpCreate)
	return &CoinBaseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CoinBase entities.
func (c *CoinBaseClient) CreateBulk(builders ...*CoinBaseCreate) *CoinBaseCreateBulk {
	return &CoinBaseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CoinBase.
func (c *CoinBaseClient) Update() *CoinBaseUpdate {
	mutation := newCoinBaseMutation(c.config, OpUpdate)
	return &CoinBaseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CoinBaseClient) UpdateOne(cb *CoinBase) *CoinBaseUpdateOne {
	mutation := newCoinBaseMutation(c.config, OpUpdateOne, withCoinBase(cb))
	return &CoinBaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CoinBaseClient) UpdateOneID(id uuid.UUID) *CoinBaseUpdateOne {
	mutation := newCoinBaseMutation(c.config, OpUpdateOne, withCoinBaseID(id))
	return &CoinBaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CoinBase.
func (c *CoinBaseClient) Delete() *CoinBaseDelete {
	mutation := newCoinBaseMutation(c.config, OpDelete)
	return &CoinBaseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CoinBaseClient) DeleteOne(cb *CoinBase) *CoinBaseDeleteOne {
	return c.DeleteOneID(cb.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CoinBaseClient) DeleteOneID(id uuid.UUID) *CoinBaseDeleteOne {
	builder := c.Delete().Where(coinbase.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CoinBaseDeleteOne{builder}
}

// Query returns a query builder for CoinBase.
func (c *CoinBaseClient) Query() *CoinBaseQuery {
	return &CoinBaseQuery{
		config: c.config,
	}
}

// Get returns a CoinBase entity by its id.
func (c *CoinBaseClient) Get(ctx context.Context, id uuid.UUID) (*CoinBase, error) {
	return c.Query().Where(coinbase.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CoinBaseClient) GetX(ctx context.Context, id uuid.UUID) *CoinBase {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CoinBaseClient) Hooks() []Hook {
	hooks := c.hooks.CoinBase
	return append(hooks[:len(hooks):len(hooks)], coinbase.Hooks[:]...)
}

// CoinExtraClient is a client for the CoinExtra schema.
type CoinExtraClient struct {
	config
}

// NewCoinExtraClient returns a client for the CoinExtra from the given config.
func NewCoinExtraClient(c config) *CoinExtraClient {
	return &CoinExtraClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coinextra.Hooks(f(g(h())))`.
func (c *CoinExtraClient) Use(hooks ...Hook) {
	c.hooks.CoinExtra = append(c.hooks.CoinExtra, hooks...)
}

// Create returns a builder for creating a CoinExtra entity.
func (c *CoinExtraClient) Create() *CoinExtraCreate {
	mutation := newCoinExtraMutation(c.config, OpCreate)
	return &CoinExtraCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CoinExtra entities.
func (c *CoinExtraClient) CreateBulk(builders ...*CoinExtraCreate) *CoinExtraCreateBulk {
	return &CoinExtraCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CoinExtra.
func (c *CoinExtraClient) Update() *CoinExtraUpdate {
	mutation := newCoinExtraMutation(c.config, OpUpdate)
	return &CoinExtraUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CoinExtraClient) UpdateOne(ce *CoinExtra) *CoinExtraUpdateOne {
	mutation := newCoinExtraMutation(c.config, OpUpdateOne, withCoinExtra(ce))
	return &CoinExtraUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CoinExtraClient) UpdateOneID(id uuid.UUID) *CoinExtraUpdateOne {
	mutation := newCoinExtraMutation(c.config, OpUpdateOne, withCoinExtraID(id))
	return &CoinExtraUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CoinExtra.
func (c *CoinExtraClient) Delete() *CoinExtraDelete {
	mutation := newCoinExtraMutation(c.config, OpDelete)
	return &CoinExtraDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CoinExtraClient) DeleteOne(ce *CoinExtra) *CoinExtraDeleteOne {
	return c.DeleteOneID(ce.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CoinExtraClient) DeleteOneID(id uuid.UUID) *CoinExtraDeleteOne {
	builder := c.Delete().Where(coinextra.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CoinExtraDeleteOne{builder}
}

// Query returns a query builder for CoinExtra.
func (c *CoinExtraClient) Query() *CoinExtraQuery {
	return &CoinExtraQuery{
		config: c.config,
	}
}

// Get returns a CoinExtra entity by its id.
func (c *CoinExtraClient) Get(ctx context.Context, id uuid.UUID) (*CoinExtra, error) {
	return c.Query().Where(coinextra.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CoinExtraClient) GetX(ctx context.Context, id uuid.UUID) *CoinExtra {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CoinExtraClient) Hooks() []Hook {
	hooks := c.hooks.CoinExtra
	return append(hooks[:len(hooks):len(hooks)], coinextra.Hooks[:]...)
}

// ExchangeRateClient is a client for the ExchangeRate schema.
type ExchangeRateClient struct {
	config
}

// NewExchangeRateClient returns a client for the ExchangeRate from the given config.
func NewExchangeRateClient(c config) *ExchangeRateClient {
	return &ExchangeRateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `exchangerate.Hooks(f(g(h())))`.
func (c *ExchangeRateClient) Use(hooks ...Hook) {
	c.hooks.ExchangeRate = append(c.hooks.ExchangeRate, hooks...)
}

// Create returns a builder for creating a ExchangeRate entity.
func (c *ExchangeRateClient) Create() *ExchangeRateCreate {
	mutation := newExchangeRateMutation(c.config, OpCreate)
	return &ExchangeRateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExchangeRate entities.
func (c *ExchangeRateClient) CreateBulk(builders ...*ExchangeRateCreate) *ExchangeRateCreateBulk {
	return &ExchangeRateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExchangeRate.
func (c *ExchangeRateClient) Update() *ExchangeRateUpdate {
	mutation := newExchangeRateMutation(c.config, OpUpdate)
	return &ExchangeRateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExchangeRateClient) UpdateOne(er *ExchangeRate) *ExchangeRateUpdateOne {
	mutation := newExchangeRateMutation(c.config, OpUpdateOne, withExchangeRate(er))
	return &ExchangeRateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExchangeRateClient) UpdateOneID(id uuid.UUID) *ExchangeRateUpdateOne {
	mutation := newExchangeRateMutation(c.config, OpUpdateOne, withExchangeRateID(id))
	return &ExchangeRateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExchangeRate.
func (c *ExchangeRateClient) Delete() *ExchangeRateDelete {
	mutation := newExchangeRateMutation(c.config, OpDelete)
	return &ExchangeRateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExchangeRateClient) DeleteOne(er *ExchangeRate) *ExchangeRateDeleteOne {
	return c.DeleteOneID(er.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *ExchangeRateClient) DeleteOneID(id uuid.UUID) *ExchangeRateDeleteOne {
	builder := c.Delete().Where(exchangerate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExchangeRateDeleteOne{builder}
}

// Query returns a query builder for ExchangeRate.
func (c *ExchangeRateClient) Query() *ExchangeRateQuery {
	return &ExchangeRateQuery{
		config: c.config,
	}
}

// Get returns a ExchangeRate entity by its id.
func (c *ExchangeRateClient) Get(ctx context.Context, id uuid.UUID) (*ExchangeRate, error) {
	return c.Query().Where(exchangerate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExchangeRateClient) GetX(ctx context.Context, id uuid.UUID) *ExchangeRate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ExchangeRateClient) Hooks() []Hook {
	hooks := c.hooks.ExchangeRate
	return append(hooks[:len(hooks):len(hooks)], exchangerate.Hooks[:]...)
}

// SettingClient is a client for the Setting schema.
type SettingClient struct {
	config
}

// NewSettingClient returns a client for the Setting from the given config.
func NewSettingClient(c config) *SettingClient {
	return &SettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `setting.Hooks(f(g(h())))`.
func (c *SettingClient) Use(hooks ...Hook) {
	c.hooks.Setting = append(c.hooks.Setting, hooks...)
}

// Create returns a builder for creating a Setting entity.
func (c *SettingClient) Create() *SettingCreate {
	mutation := newSettingMutation(c.config, OpCreate)
	return &SettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Setting entities.
func (c *SettingClient) CreateBulk(builders ...*SettingCreate) *SettingCreateBulk {
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Setting.
func (c *SettingClient) Update() *SettingUpdate {
	mutation := newSettingMutation(c.config, OpUpdate)
	return &SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingClient) UpdateOne(s *Setting) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSetting(s))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingClient) UpdateOneID(id uuid.UUID) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSettingID(id))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Setting.
func (c *SettingClient) Delete() *SettingDelete {
	mutation := newSettingMutation(c.config, OpDelete)
	return &SettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingClient) DeleteOne(s *Setting) *SettingDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *SettingClient) DeleteOneID(id uuid.UUID) *SettingDeleteOne {
	builder := c.Delete().Where(setting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingDeleteOne{builder}
}

// Query returns a query builder for Setting.
func (c *SettingClient) Query() *SettingQuery {
	return &SettingQuery{
		config: c.config,
	}
}

// Get returns a Setting entity by its id.
func (c *SettingClient) Get(ctx context.Context, id uuid.UUID) (*Setting, error) {
	return c.Query().Where(setting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingClient) GetX(ctx context.Context, id uuid.UUID) *Setting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingClient) Hooks() []Hook {
	hooks := c.hooks.Setting
	return append(hooks[:len(hooks):len(hooks)], setting.Hooks[:]...)
}

// TranClient is a client for the Tran schema.
type TranClient struct {
	config
}

// NewTranClient returns a client for the Tran from the given config.
func NewTranClient(c config) *TranClient {
	return &TranClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tran.Hooks(f(g(h())))`.
func (c *TranClient) Use(hooks ...Hook) {
	c.hooks.Tran = append(c.hooks.Tran, hooks...)
}

// Create returns a builder for creating a Tran entity.
func (c *TranClient) Create() *TranCreate {
	mutation := newTranMutation(c.config, OpCreate)
	return &TranCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tran entities.
func (c *TranClient) CreateBulk(builders ...*TranCreate) *TranCreateBulk {
	return &TranCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tran.
func (c *TranClient) Update() *TranUpdate {
	mutation := newTranMutation(c.config, OpUpdate)
	return &TranUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TranClient) UpdateOne(t *Tran) *TranUpdateOne {
	mutation := newTranMutation(c.config, OpUpdateOne, withTran(t))
	return &TranUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TranClient) UpdateOneID(id uuid.UUID) *TranUpdateOne {
	mutation := newTranMutation(c.config, OpUpdateOne, withTranID(id))
	return &TranUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tran.
func (c *TranClient) Delete() *TranDelete {
	mutation := newTranMutation(c.config, OpDelete)
	return &TranDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TranClient) DeleteOne(t *Tran) *TranDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *TranClient) DeleteOneID(id uuid.UUID) *TranDeleteOne {
	builder := c.Delete().Where(tran.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TranDeleteOne{builder}
}

// Query returns a query builder for Tran.
func (c *TranClient) Query() *TranQuery {
	return &TranQuery{
		config: c.config,
	}
}

// Get returns a Tran entity by its id.
func (c *TranClient) Get(ctx context.Context, id uuid.UUID) (*Tran, error) {
	return c.Query().Where(tran.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TranClient) GetX(ctx context.Context, id uuid.UUID) *Tran {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TranClient) Hooks() []Hook {
	hooks := c.hooks.Tran
	return append(hooks[:len(hooks):len(hooks)], tran.Hooks[:]...)
}
