// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/tran"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Tran is the client for interacting with the Tran builders.
	Tran *TranClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Tran = NewTranClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Tran:   NewTranClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Tran:   NewTranClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Tran.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Tran.Use(hooks...)
}

// TranClient is a client for the Tran schema.
type TranClient struct {
	config
}

// NewTranClient returns a client for the Tran from the given config.
func NewTranClient(c config) *TranClient {
	return &TranClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tran.Hooks(f(g(h())))`.
func (c *TranClient) Use(hooks ...Hook) {
	c.hooks.Tran = append(c.hooks.Tran, hooks...)
}

// Create returns a builder for creating a Tran entity.
func (c *TranClient) Create() *TranCreate {
	mutation := newTranMutation(c.config, OpCreate)
	return &TranCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tran entities.
func (c *TranClient) CreateBulk(builders ...*TranCreate) *TranCreateBulk {
	return &TranCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tran.
func (c *TranClient) Update() *TranUpdate {
	mutation := newTranMutation(c.config, OpUpdate)
	return &TranUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TranClient) UpdateOne(t *Tran) *TranUpdateOne {
	mutation := newTranMutation(c.config, OpUpdateOne, withTran(t))
	return &TranUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TranClient) UpdateOneID(id uuid.UUID) *TranUpdateOne {
	mutation := newTranMutation(c.config, OpUpdateOne, withTranID(id))
	return &TranUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tran.
func (c *TranClient) Delete() *TranDelete {
	mutation := newTranMutation(c.config, OpDelete)
	return &TranDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TranClient) DeleteOne(t *Tran) *TranDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *TranClient) DeleteOneID(id uuid.UUID) *TranDeleteOne {
	builder := c.Delete().Where(tran.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TranDeleteOne{builder}
}

// Query returns a query builder for Tran.
func (c *TranClient) Query() *TranQuery {
	return &TranQuery{
		config: c.config,
	}
}

// Get returns a Tran entity by its id.
func (c *TranClient) Get(ctx context.Context, id uuid.UUID) (*Tran, error) {
	return c.Query().Where(tran.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TranClient) GetX(ctx context.Context, id uuid.UUID) *Tran {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TranClient) Hooks() []Hook {
	hooks := c.hooks.Tran
	return append(hooks[:len(hooks):len(hooks)], tran.Hooks[:]...)
}
