// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/currencyvalue"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CurrencyValue is the model entity for the CurrencyValue schema.
type CurrencyValue struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// FeedSourceID holds the value of the "feed_source_id" field.
	FeedSourceID uuid.UUID `json:"feed_source_id,omitempty"`
	// MarketValueHigh holds the value of the "market_value_high" field.
	MarketValueHigh decimal.Decimal `json:"market_value_high,omitempty"`
	// MarketValueLow holds the value of the "market_value_low" field.
	MarketValueLow decimal.Decimal `json:"market_value_low,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CurrencyValue) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case currencyvalue.FieldMarketValueHigh, currencyvalue.FieldMarketValueLow:
			values[i] = new(decimal.Decimal)
		case currencyvalue.FieldCreatedAt, currencyvalue.FieldUpdatedAt, currencyvalue.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case currencyvalue.FieldID, currencyvalue.FieldCoinTypeID, currencyvalue.FieldFeedSourceID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CurrencyValue", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CurrencyValue fields.
func (cv *CurrencyValue) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case currencyvalue.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cv.ID = *value
			}
		case currencyvalue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cv.CreatedAt = uint32(value.Int64)
			}
		case currencyvalue.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cv.UpdatedAt = uint32(value.Int64)
			}
		case currencyvalue.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				cv.DeletedAt = uint32(value.Int64)
			}
		case currencyvalue.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				cv.CoinTypeID = *value
			}
		case currencyvalue.FieldFeedSourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field feed_source_id", values[i])
			} else if value != nil {
				cv.FeedSourceID = *value
			}
		case currencyvalue.FieldMarketValueHigh:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field market_value_high", values[i])
			} else if value != nil {
				cv.MarketValueHigh = *value
			}
		case currencyvalue.FieldMarketValueLow:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field market_value_low", values[i])
			} else if value != nil {
				cv.MarketValueLow = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CurrencyValue.
// Note that you need to call CurrencyValue.Unwrap() before calling this method if this CurrencyValue
// was returned from a transaction, and the transaction was committed or rolled back.
func (cv *CurrencyValue) Update() *CurrencyValueUpdateOne {
	return (&CurrencyValueClient{config: cv.config}).UpdateOne(cv)
}

// Unwrap unwraps the CurrencyValue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cv *CurrencyValue) Unwrap() *CurrencyValue {
	_tx, ok := cv.config.driver.(*txDriver)
	if !ok {
		panic("ent: CurrencyValue is not a transactional entity")
	}
	cv.config.driver = _tx.drv
	return cv
}

// String implements the fmt.Stringer.
func (cv *CurrencyValue) String() string {
	var builder strings.Builder
	builder.WriteString("CurrencyValue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cv.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", cv.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", cv.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", cv.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", cv.CoinTypeID))
	builder.WriteString(", ")
	builder.WriteString("feed_source_id=")
	builder.WriteString(fmt.Sprintf("%v", cv.FeedSourceID))
	builder.WriteString(", ")
	builder.WriteString("market_value_high=")
	builder.WriteString(fmt.Sprintf("%v", cv.MarketValueHigh))
	builder.WriteString(", ")
	builder.WriteString("market_value_low=")
	builder.WriteString(fmt.Sprintf("%v", cv.MarketValueLow))
	builder.WriteByte(')')
	return builder.String()
}

// CurrencyValues is a parsable slice of CurrencyValue.
type CurrencyValues []*CurrencyValue

func (cv CurrencyValues) config(cfg config) {
	for _i := range cv {
		cv[_i].config = cfg
	}
}
