// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/latestcurrency"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LatestCurrency is the model entity for the LatestCurrency schema.
type LatestCurrency struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// FeedType holds the value of the "feed_type" field.
	FeedType string `json:"feed_type,omitempty"`
	// MarketValueHigh holds the value of the "market_value_high" field.
	MarketValueHigh decimal.Decimal `json:"market_value_high,omitempty"`
	// MarketValueLow holds the value of the "market_value_low" field.
	MarketValueLow decimal.Decimal `json:"market_value_low,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LatestCurrency) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case latestcurrency.FieldMarketValueHigh, latestcurrency.FieldMarketValueLow:
			values[i] = new(decimal.Decimal)
		case latestcurrency.FieldCreatedAt, latestcurrency.FieldUpdatedAt, latestcurrency.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case latestcurrency.FieldFeedType:
			values[i] = new(sql.NullString)
		case latestcurrency.FieldID, latestcurrency.FieldCoinTypeID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type LatestCurrency", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LatestCurrency fields.
func (lc *LatestCurrency) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case latestcurrency.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				lc.ID = *value
			}
		case latestcurrency.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lc.CreatedAt = uint32(value.Int64)
			}
		case latestcurrency.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				lc.UpdatedAt = uint32(value.Int64)
			}
		case latestcurrency.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				lc.DeletedAt = uint32(value.Int64)
			}
		case latestcurrency.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				lc.CoinTypeID = *value
			}
		case latestcurrency.FieldFeedType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feed_type", values[i])
			} else if value.Valid {
				lc.FeedType = value.String
			}
		case latestcurrency.FieldMarketValueHigh:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field market_value_high", values[i])
			} else if value != nil {
				lc.MarketValueHigh = *value
			}
		case latestcurrency.FieldMarketValueLow:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field market_value_low", values[i])
			} else if value != nil {
				lc.MarketValueLow = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this LatestCurrency.
// Note that you need to call LatestCurrency.Unwrap() before calling this method if this LatestCurrency
// was returned from a transaction, and the transaction was committed or rolled back.
func (lc *LatestCurrency) Update() *LatestCurrencyUpdateOne {
	return (&LatestCurrencyClient{config: lc.config}).UpdateOne(lc)
}

// Unwrap unwraps the LatestCurrency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lc *LatestCurrency) Unwrap() *LatestCurrency {
	_tx, ok := lc.config.driver.(*txDriver)
	if !ok {
		panic("ent: LatestCurrency is not a transactional entity")
	}
	lc.config.driver = _tx.drv
	return lc
}

// String implements the fmt.Stringer.
func (lc *LatestCurrency) String() string {
	var builder strings.Builder
	builder.WriteString("LatestCurrency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", lc.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", lc.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", lc.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", lc.CoinTypeID))
	builder.WriteString(", ")
	builder.WriteString("feed_type=")
	builder.WriteString(lc.FeedType)
	builder.WriteString(", ")
	builder.WriteString("market_value_high=")
	builder.WriteString(fmt.Sprintf("%v", lc.MarketValueHigh))
	builder.WriteString(", ")
	builder.WriteString("market_value_low=")
	builder.WriteString(fmt.Sprintf("%v", lc.MarketValueLow))
	builder.WriteByte(')')
	return builder.String()
}

// LatestCurrencies is a parsable slice of LatestCurrency.
type LatestCurrencies []*LatestCurrency

func (lc LatestCurrencies) config(cfg config) {
	for _i := range lc {
		lc[_i].config = cfg
	}
}
