// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/latestcurrency"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/predicate"
)

// LatestCurrencyDelete is the builder for deleting a LatestCurrency entity.
type LatestCurrencyDelete struct {
	config
	hooks    []Hook
	mutation *LatestCurrencyMutation
}

// Where appends a list predicates to the LatestCurrencyDelete builder.
func (lcd *LatestCurrencyDelete) Where(ps ...predicate.LatestCurrency) *LatestCurrencyDelete {
	lcd.mutation.Where(ps...)
	return lcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lcd *LatestCurrencyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lcd.hooks) == 0 {
		affected, err = lcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LatestCurrencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcd.mutation = mutation
			affected, err = lcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lcd.hooks) - 1; i >= 0; i-- {
			if lcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcd *LatestCurrencyDelete) ExecX(ctx context.Context) int {
	n, err := lcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lcd *LatestCurrencyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: latestcurrency.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: latestcurrency.FieldID,
			},
		},
	}
	if ps := lcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// LatestCurrencyDeleteOne is the builder for deleting a single LatestCurrency entity.
type LatestCurrencyDeleteOne struct {
	lcd *LatestCurrencyDelete
}

// Exec executes the deletion query.
func (lcdo *LatestCurrencyDeleteOne) Exec(ctx context.Context) error {
	n, err := lcdo.lcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{latestcurrency.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lcdo *LatestCurrencyDeleteOne) ExecX(ctx context.Context) {
	lcdo.lcd.ExecX(ctx)
}
