// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/latestcurrency"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LatestCurrencyUpdate is the builder for updating LatestCurrency entities.
type LatestCurrencyUpdate struct {
	config
	hooks     []Hook
	mutation  *LatestCurrencyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LatestCurrencyUpdate builder.
func (lcu *LatestCurrencyUpdate) Where(ps ...predicate.LatestCurrency) *LatestCurrencyUpdate {
	lcu.mutation.Where(ps...)
	return lcu
}

// SetCreatedAt sets the "created_at" field.
func (lcu *LatestCurrencyUpdate) SetCreatedAt(u uint32) *LatestCurrencyUpdate {
	lcu.mutation.ResetCreatedAt()
	lcu.mutation.SetCreatedAt(u)
	return lcu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableCreatedAt(u *uint32) *LatestCurrencyUpdate {
	if u != nil {
		lcu.SetCreatedAt(*u)
	}
	return lcu
}

// AddCreatedAt adds u to the "created_at" field.
func (lcu *LatestCurrencyUpdate) AddCreatedAt(u int32) *LatestCurrencyUpdate {
	lcu.mutation.AddCreatedAt(u)
	return lcu
}

// SetUpdatedAt sets the "updated_at" field.
func (lcu *LatestCurrencyUpdate) SetUpdatedAt(u uint32) *LatestCurrencyUpdate {
	lcu.mutation.ResetUpdatedAt()
	lcu.mutation.SetUpdatedAt(u)
	return lcu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (lcu *LatestCurrencyUpdate) AddUpdatedAt(u int32) *LatestCurrencyUpdate {
	lcu.mutation.AddUpdatedAt(u)
	return lcu
}

// SetDeletedAt sets the "deleted_at" field.
func (lcu *LatestCurrencyUpdate) SetDeletedAt(u uint32) *LatestCurrencyUpdate {
	lcu.mutation.ResetDeletedAt()
	lcu.mutation.SetDeletedAt(u)
	return lcu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableDeletedAt(u *uint32) *LatestCurrencyUpdate {
	if u != nil {
		lcu.SetDeletedAt(*u)
	}
	return lcu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (lcu *LatestCurrencyUpdate) AddDeletedAt(u int32) *LatestCurrencyUpdate {
	lcu.mutation.AddDeletedAt(u)
	return lcu
}

// SetCoinTypeID sets the "coin_type_id" field.
func (lcu *LatestCurrencyUpdate) SetCoinTypeID(u uuid.UUID) *LatestCurrencyUpdate {
	lcu.mutation.SetCoinTypeID(u)
	return lcu
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableCoinTypeID(u *uuid.UUID) *LatestCurrencyUpdate {
	if u != nil {
		lcu.SetCoinTypeID(*u)
	}
	return lcu
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (lcu *LatestCurrencyUpdate) ClearCoinTypeID() *LatestCurrencyUpdate {
	lcu.mutation.ClearCoinTypeID()
	return lcu
}

// SetFeedType sets the "feed_type" field.
func (lcu *LatestCurrencyUpdate) SetFeedType(s string) *LatestCurrencyUpdate {
	lcu.mutation.SetFeedType(s)
	return lcu
}

// SetNillableFeedType sets the "feed_type" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableFeedType(s *string) *LatestCurrencyUpdate {
	if s != nil {
		lcu.SetFeedType(*s)
	}
	return lcu
}

// ClearFeedType clears the value of the "feed_type" field.
func (lcu *LatestCurrencyUpdate) ClearFeedType() *LatestCurrencyUpdate {
	lcu.mutation.ClearFeedType()
	return lcu
}

// SetMarketValueHigh sets the "market_value_high" field.
func (lcu *LatestCurrencyUpdate) SetMarketValueHigh(d decimal.Decimal) *LatestCurrencyUpdate {
	lcu.mutation.SetMarketValueHigh(d)
	return lcu
}

// SetNillableMarketValueHigh sets the "market_value_high" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableMarketValueHigh(d *decimal.Decimal) *LatestCurrencyUpdate {
	if d != nil {
		lcu.SetMarketValueHigh(*d)
	}
	return lcu
}

// ClearMarketValueHigh clears the value of the "market_value_high" field.
func (lcu *LatestCurrencyUpdate) ClearMarketValueHigh() *LatestCurrencyUpdate {
	lcu.mutation.ClearMarketValueHigh()
	return lcu
}

// SetMarketValueLow sets the "market_value_low" field.
func (lcu *LatestCurrencyUpdate) SetMarketValueLow(d decimal.Decimal) *LatestCurrencyUpdate {
	lcu.mutation.SetMarketValueLow(d)
	return lcu
}

// SetNillableMarketValueLow sets the "market_value_low" field if the given value is not nil.
func (lcu *LatestCurrencyUpdate) SetNillableMarketValueLow(d *decimal.Decimal) *LatestCurrencyUpdate {
	if d != nil {
		lcu.SetMarketValueLow(*d)
	}
	return lcu
}

// ClearMarketValueLow clears the value of the "market_value_low" field.
func (lcu *LatestCurrencyUpdate) ClearMarketValueLow() *LatestCurrencyUpdate {
	lcu.mutation.ClearMarketValueLow()
	return lcu
}

// Mutation returns the LatestCurrencyMutation object of the builder.
func (lcu *LatestCurrencyUpdate) Mutation() *LatestCurrencyMutation {
	return lcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lcu *LatestCurrencyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := lcu.defaults(); err != nil {
		return 0, err
	}
	if len(lcu.hooks) == 0 {
		affected, err = lcu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LatestCurrencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcu.mutation = mutation
			affected, err = lcu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lcu.hooks) - 1; i >= 0; i-- {
			if lcu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lcu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lcu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lcu *LatestCurrencyUpdate) SaveX(ctx context.Context) int {
	affected, err := lcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lcu *LatestCurrencyUpdate) Exec(ctx context.Context) error {
	_, err := lcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcu *LatestCurrencyUpdate) ExecX(ctx context.Context) {
	if err := lcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lcu *LatestCurrencyUpdate) defaults() error {
	if _, ok := lcu.mutation.UpdatedAt(); !ok {
		if latestcurrency.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized latestcurrency.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := latestcurrency.UpdateDefaultUpdatedAt()
		lcu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lcu *LatestCurrencyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LatestCurrencyUpdate {
	lcu.modifiers = append(lcu.modifiers, modifiers...)
	return lcu
}

func (lcu *LatestCurrencyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   latestcurrency.Table,
			Columns: latestcurrency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: latestcurrency.FieldID,
			},
		},
	}
	if ps := lcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldCreatedAt,
		})
	}
	if value, ok := lcu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldCreatedAt,
		})
	}
	if value, ok := lcu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldUpdatedAt,
		})
	}
	if value, ok := lcu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldUpdatedAt,
		})
	}
	if value, ok := lcu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldDeletedAt,
		})
	}
	if value, ok := lcu.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldDeletedAt,
		})
	}
	if value, ok := lcu.mutation.CoinTypeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: latestcurrency.FieldCoinTypeID,
		})
	}
	if lcu.mutation.CoinTypeIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: latestcurrency.FieldCoinTypeID,
		})
	}
	if value, ok := lcu.mutation.FeedType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: latestcurrency.FieldFeedType,
		})
	}
	if lcu.mutation.FeedTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: latestcurrency.FieldFeedType,
		})
	}
	if value, ok := lcu.mutation.MarketValueHigh(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: latestcurrency.FieldMarketValueHigh,
		})
	}
	if lcu.mutation.MarketValueHighCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: latestcurrency.FieldMarketValueHigh,
		})
	}
	if value, ok := lcu.mutation.MarketValueLow(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: latestcurrency.FieldMarketValueLow,
		})
	}
	if lcu.mutation.MarketValueLowCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: latestcurrency.FieldMarketValueLow,
		})
	}
	_spec.Modifiers = lcu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, lcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{latestcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// LatestCurrencyUpdateOne is the builder for updating a single LatestCurrency entity.
type LatestCurrencyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LatestCurrencyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (lcuo *LatestCurrencyUpdateOne) SetCreatedAt(u uint32) *LatestCurrencyUpdateOne {
	lcuo.mutation.ResetCreatedAt()
	lcuo.mutation.SetCreatedAt(u)
	return lcuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableCreatedAt(u *uint32) *LatestCurrencyUpdateOne {
	if u != nil {
		lcuo.SetCreatedAt(*u)
	}
	return lcuo
}

// AddCreatedAt adds u to the "created_at" field.
func (lcuo *LatestCurrencyUpdateOne) AddCreatedAt(u int32) *LatestCurrencyUpdateOne {
	lcuo.mutation.AddCreatedAt(u)
	return lcuo
}

// SetUpdatedAt sets the "updated_at" field.
func (lcuo *LatestCurrencyUpdateOne) SetUpdatedAt(u uint32) *LatestCurrencyUpdateOne {
	lcuo.mutation.ResetUpdatedAt()
	lcuo.mutation.SetUpdatedAt(u)
	return lcuo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (lcuo *LatestCurrencyUpdateOne) AddUpdatedAt(u int32) *LatestCurrencyUpdateOne {
	lcuo.mutation.AddUpdatedAt(u)
	return lcuo
}

// SetDeletedAt sets the "deleted_at" field.
func (lcuo *LatestCurrencyUpdateOne) SetDeletedAt(u uint32) *LatestCurrencyUpdateOne {
	lcuo.mutation.ResetDeletedAt()
	lcuo.mutation.SetDeletedAt(u)
	return lcuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableDeletedAt(u *uint32) *LatestCurrencyUpdateOne {
	if u != nil {
		lcuo.SetDeletedAt(*u)
	}
	return lcuo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (lcuo *LatestCurrencyUpdateOne) AddDeletedAt(u int32) *LatestCurrencyUpdateOne {
	lcuo.mutation.AddDeletedAt(u)
	return lcuo
}

// SetCoinTypeID sets the "coin_type_id" field.
func (lcuo *LatestCurrencyUpdateOne) SetCoinTypeID(u uuid.UUID) *LatestCurrencyUpdateOne {
	lcuo.mutation.SetCoinTypeID(u)
	return lcuo
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableCoinTypeID(u *uuid.UUID) *LatestCurrencyUpdateOne {
	if u != nil {
		lcuo.SetCoinTypeID(*u)
	}
	return lcuo
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (lcuo *LatestCurrencyUpdateOne) ClearCoinTypeID() *LatestCurrencyUpdateOne {
	lcuo.mutation.ClearCoinTypeID()
	return lcuo
}

// SetFeedType sets the "feed_type" field.
func (lcuo *LatestCurrencyUpdateOne) SetFeedType(s string) *LatestCurrencyUpdateOne {
	lcuo.mutation.SetFeedType(s)
	return lcuo
}

// SetNillableFeedType sets the "feed_type" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableFeedType(s *string) *LatestCurrencyUpdateOne {
	if s != nil {
		lcuo.SetFeedType(*s)
	}
	return lcuo
}

// ClearFeedType clears the value of the "feed_type" field.
func (lcuo *LatestCurrencyUpdateOne) ClearFeedType() *LatestCurrencyUpdateOne {
	lcuo.mutation.ClearFeedType()
	return lcuo
}

// SetMarketValueHigh sets the "market_value_high" field.
func (lcuo *LatestCurrencyUpdateOne) SetMarketValueHigh(d decimal.Decimal) *LatestCurrencyUpdateOne {
	lcuo.mutation.SetMarketValueHigh(d)
	return lcuo
}

// SetNillableMarketValueHigh sets the "market_value_high" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableMarketValueHigh(d *decimal.Decimal) *LatestCurrencyUpdateOne {
	if d != nil {
		lcuo.SetMarketValueHigh(*d)
	}
	return lcuo
}

// ClearMarketValueHigh clears the value of the "market_value_high" field.
func (lcuo *LatestCurrencyUpdateOne) ClearMarketValueHigh() *LatestCurrencyUpdateOne {
	lcuo.mutation.ClearMarketValueHigh()
	return lcuo
}

// SetMarketValueLow sets the "market_value_low" field.
func (lcuo *LatestCurrencyUpdateOne) SetMarketValueLow(d decimal.Decimal) *LatestCurrencyUpdateOne {
	lcuo.mutation.SetMarketValueLow(d)
	return lcuo
}

// SetNillableMarketValueLow sets the "market_value_low" field if the given value is not nil.
func (lcuo *LatestCurrencyUpdateOne) SetNillableMarketValueLow(d *decimal.Decimal) *LatestCurrencyUpdateOne {
	if d != nil {
		lcuo.SetMarketValueLow(*d)
	}
	return lcuo
}

// ClearMarketValueLow clears the value of the "market_value_low" field.
func (lcuo *LatestCurrencyUpdateOne) ClearMarketValueLow() *LatestCurrencyUpdateOne {
	lcuo.mutation.ClearMarketValueLow()
	return lcuo
}

// Mutation returns the LatestCurrencyMutation object of the builder.
func (lcuo *LatestCurrencyUpdateOne) Mutation() *LatestCurrencyMutation {
	return lcuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lcuo *LatestCurrencyUpdateOne) Select(field string, fields ...string) *LatestCurrencyUpdateOne {
	lcuo.fields = append([]string{field}, fields...)
	return lcuo
}

// Save executes the query and returns the updated LatestCurrency entity.
func (lcuo *LatestCurrencyUpdateOne) Save(ctx context.Context) (*LatestCurrency, error) {
	var (
		err  error
		node *LatestCurrency
	)
	if err := lcuo.defaults(); err != nil {
		return nil, err
	}
	if len(lcuo.hooks) == 0 {
		node, err = lcuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LatestCurrencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcuo.mutation = mutation
			node, err = lcuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(lcuo.hooks) - 1; i >= 0; i-- {
			if lcuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lcuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, lcuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*LatestCurrency)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from LatestCurrencyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (lcuo *LatestCurrencyUpdateOne) SaveX(ctx context.Context) *LatestCurrency {
	node, err := lcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lcuo *LatestCurrencyUpdateOne) Exec(ctx context.Context) error {
	_, err := lcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcuo *LatestCurrencyUpdateOne) ExecX(ctx context.Context) {
	if err := lcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lcuo *LatestCurrencyUpdateOne) defaults() error {
	if _, ok := lcuo.mutation.UpdatedAt(); !ok {
		if latestcurrency.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized latestcurrency.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := latestcurrency.UpdateDefaultUpdatedAt()
		lcuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lcuo *LatestCurrencyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LatestCurrencyUpdateOne {
	lcuo.modifiers = append(lcuo.modifiers, modifiers...)
	return lcuo
}

func (lcuo *LatestCurrencyUpdateOne) sqlSave(ctx context.Context) (_node *LatestCurrency, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   latestcurrency.Table,
			Columns: latestcurrency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: latestcurrency.FieldID,
			},
		},
	}
	id, ok := lcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LatestCurrency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, latestcurrency.FieldID)
		for _, f := range fields {
			if !latestcurrency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != latestcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldCreatedAt,
		})
	}
	if value, ok := lcuo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldCreatedAt,
		})
	}
	if value, ok := lcuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldUpdatedAt,
		})
	}
	if value, ok := lcuo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldUpdatedAt,
		})
	}
	if value, ok := lcuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldDeletedAt,
		})
	}
	if value, ok := lcuo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: latestcurrency.FieldDeletedAt,
		})
	}
	if value, ok := lcuo.mutation.CoinTypeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: latestcurrency.FieldCoinTypeID,
		})
	}
	if lcuo.mutation.CoinTypeIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Column: latestcurrency.FieldCoinTypeID,
		})
	}
	if value, ok := lcuo.mutation.FeedType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: latestcurrency.FieldFeedType,
		})
	}
	if lcuo.mutation.FeedTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: latestcurrency.FieldFeedType,
		})
	}
	if value, ok := lcuo.mutation.MarketValueHigh(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: latestcurrency.FieldMarketValueHigh,
		})
	}
	if lcuo.mutation.MarketValueHighCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: latestcurrency.FieldMarketValueHigh,
		})
	}
	if value, ok := lcuo.mutation.MarketValueLow(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: latestcurrency.FieldMarketValueLow,
		})
	}
	if lcuo.mutation.MarketValueLowCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Column: latestcurrency.FieldMarketValueLow,
		})
	}
	_spec.Modifiers = lcuo.modifiers
	_node = &LatestCurrency{config: lcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{latestcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
