// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/legalcurrency"
	"github.com/NpoolPlatform/chain-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// LegalCurrencyQuery is the builder for querying LegalCurrency entities.
type LegalCurrencyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LegalCurrency
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LegalCurrencyQuery builder.
func (lcq *LegalCurrencyQuery) Where(ps ...predicate.LegalCurrency) *LegalCurrencyQuery {
	lcq.predicates = append(lcq.predicates, ps...)
	return lcq
}

// Limit adds a limit step to the query.
func (lcq *LegalCurrencyQuery) Limit(limit int) *LegalCurrencyQuery {
	lcq.limit = &limit
	return lcq
}

// Offset adds an offset step to the query.
func (lcq *LegalCurrencyQuery) Offset(offset int) *LegalCurrencyQuery {
	lcq.offset = &offset
	return lcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lcq *LegalCurrencyQuery) Unique(unique bool) *LegalCurrencyQuery {
	lcq.unique = &unique
	return lcq
}

// Order adds an order step to the query.
func (lcq *LegalCurrencyQuery) Order(o ...OrderFunc) *LegalCurrencyQuery {
	lcq.order = append(lcq.order, o...)
	return lcq
}

// First returns the first LegalCurrency entity from the query.
// Returns a *NotFoundError when no LegalCurrency was found.
func (lcq *LegalCurrencyQuery) First(ctx context.Context) (*LegalCurrency, error) {
	nodes, err := lcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{legalcurrency.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) FirstX(ctx context.Context) *LegalCurrency {
	node, err := lcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LegalCurrency ID from the query.
// Returns a *NotFoundError when no LegalCurrency ID was found.
func (lcq *LegalCurrencyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{legalcurrency.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := lcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LegalCurrency entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LegalCurrency entity is found.
// Returns a *NotFoundError when no LegalCurrency entities are found.
func (lcq *LegalCurrencyQuery) Only(ctx context.Context) (*LegalCurrency, error) {
	nodes, err := lcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{legalcurrency.Label}
	default:
		return nil, &NotSingularError{legalcurrency.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) OnlyX(ctx context.Context) *LegalCurrency {
	node, err := lcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LegalCurrency ID in the query.
// Returns a *NotSingularError when more than one LegalCurrency ID is found.
// Returns a *NotFoundError when no entities are found.
func (lcq *LegalCurrencyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{legalcurrency.Label}
	default:
		err = &NotSingularError{legalcurrency.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := lcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LegalCurrencies.
func (lcq *LegalCurrencyQuery) All(ctx context.Context) ([]*LegalCurrency, error) {
	if err := lcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) AllX(ctx context.Context) []*LegalCurrency {
	nodes, err := lcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LegalCurrency IDs.
func (lcq *LegalCurrencyQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := lcq.Select(legalcurrency.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := lcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lcq *LegalCurrencyQuery) Count(ctx context.Context) (int, error) {
	if err := lcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) CountX(ctx context.Context) int {
	count, err := lcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lcq *LegalCurrencyQuery) Exist(ctx context.Context) (bool, error) {
	if err := lcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lcq *LegalCurrencyQuery) ExistX(ctx context.Context) bool {
	exist, err := lcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LegalCurrencyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lcq *LegalCurrencyQuery) Clone() *LegalCurrencyQuery {
	if lcq == nil {
		return nil
	}
	return &LegalCurrencyQuery{
		config:     lcq.config,
		limit:      lcq.limit,
		offset:     lcq.offset,
		order:      append([]OrderFunc{}, lcq.order...),
		predicates: append([]predicate.LegalCurrency{}, lcq.predicates...),
		// clone intermediate query.
		sql:    lcq.sql.Clone(),
		path:   lcq.path,
		unique: lcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LegalCurrency.Query().
//		GroupBy(legalcurrency.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lcq *LegalCurrencyQuery) GroupBy(field string, fields ...string) *LegalCurrencyGroupBy {
	grbuild := &LegalCurrencyGroupBy{config: lcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lcq.sqlQuery(ctx), nil
	}
	grbuild.label = legalcurrency.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.LegalCurrency.Query().
//		Select(legalcurrency.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (lcq *LegalCurrencyQuery) Select(fields ...string) *LegalCurrencySelect {
	lcq.fields = append(lcq.fields, fields...)
	selbuild := &LegalCurrencySelect{LegalCurrencyQuery: lcq}
	selbuild.label = legalcurrency.Label
	selbuild.flds, selbuild.scan = &lcq.fields, selbuild.Scan
	return selbuild
}

func (lcq *LegalCurrencyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lcq.fields {
		if !legalcurrency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lcq.path != nil {
		prev, err := lcq.path(ctx)
		if err != nil {
			return err
		}
		lcq.sql = prev
	}
	if legalcurrency.Policy == nil {
		return errors.New("ent: uninitialized legalcurrency.Policy (forgotten import ent/runtime?)")
	}
	if err := legalcurrency.Policy.EvalQuery(ctx, lcq); err != nil {
		return err
	}
	return nil
}

func (lcq *LegalCurrencyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LegalCurrency, error) {
	var (
		nodes = []*LegalCurrency{}
		_spec = lcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*LegalCurrency).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &LegalCurrency{config: lcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(lcq.modifiers) > 0 {
		_spec.Modifiers = lcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lcq *LegalCurrencyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lcq.querySpec()
	if len(lcq.modifiers) > 0 {
		_spec.Modifiers = lcq.modifiers
	}
	_spec.Node.Columns = lcq.fields
	if len(lcq.fields) > 0 {
		_spec.Unique = lcq.unique != nil && *lcq.unique
	}
	return sqlgraph.CountNodes(ctx, lcq.driver, _spec)
}

func (lcq *LegalCurrencyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (lcq *LegalCurrencyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   legalcurrency.Table,
			Columns: legalcurrency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: legalcurrency.FieldID,
			},
		},
		From:   lcq.sql,
		Unique: true,
	}
	if unique := lcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, legalcurrency.FieldID)
		for i := range fields {
			if fields[i] != legalcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lcq *LegalCurrencyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lcq.driver.Dialect())
	t1 := builder.Table(legalcurrency.Table)
	columns := lcq.fields
	if len(columns) == 0 {
		columns = legalcurrency.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lcq.sql != nil {
		selector = lcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lcq.unique != nil && *lcq.unique {
		selector.Distinct()
	}
	for _, m := range lcq.modifiers {
		m(selector)
	}
	for _, p := range lcq.predicates {
		p(selector)
	}
	for _, p := range lcq.order {
		p(selector)
	}
	if offset := lcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (lcq *LegalCurrencyQuery) ForUpdate(opts ...sql.LockOption) *LegalCurrencyQuery {
	if lcq.driver.Dialect() == dialect.Postgres {
		lcq.Unique(false)
	}
	lcq.modifiers = append(lcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return lcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (lcq *LegalCurrencyQuery) ForShare(opts ...sql.LockOption) *LegalCurrencyQuery {
	if lcq.driver.Dialect() == dialect.Postgres {
		lcq.Unique(false)
	}
	lcq.modifiers = append(lcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return lcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lcq *LegalCurrencyQuery) Modify(modifiers ...func(s *sql.Selector)) *LegalCurrencySelect {
	lcq.modifiers = append(lcq.modifiers, modifiers...)
	return lcq.Select()
}

// LegalCurrencyGroupBy is the group-by builder for LegalCurrency entities.
type LegalCurrencyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lcgb *LegalCurrencyGroupBy) Aggregate(fns ...AggregateFunc) *LegalCurrencyGroupBy {
	lcgb.fns = append(lcgb.fns, fns...)
	return lcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lcgb *LegalCurrencyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lcgb.path(ctx)
	if err != nil {
		return err
	}
	lcgb.sql = query
	return lcgb.sqlScan(ctx, v)
}

func (lcgb *LegalCurrencyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lcgb.fields {
		if !legalcurrency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lcgb *LegalCurrencyGroupBy) sqlQuery() *sql.Selector {
	selector := lcgb.sql.Select()
	aggregation := make([]string, 0, len(lcgb.fns))
	for _, fn := range lcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lcgb.fields)+len(lcgb.fns))
		for _, f := range lcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lcgb.fields...)...)
}

// LegalCurrencySelect is the builder for selecting fields of LegalCurrency entities.
type LegalCurrencySelect struct {
	*LegalCurrencyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lcs *LegalCurrencySelect) Scan(ctx context.Context, v interface{}) error {
	if err := lcs.prepareQuery(ctx); err != nil {
		return err
	}
	lcs.sql = lcs.LegalCurrencyQuery.sqlQuery(ctx)
	return lcs.sqlScan(ctx, v)
}

func (lcs *LegalCurrencySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lcs.sql.Query()
	if err := lcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lcs *LegalCurrencySelect) Modify(modifiers ...func(s *sql.Selector)) *LegalCurrencySelect {
	lcs.modifiers = append(lcs.modifiers, modifiers...)
	return lcs
}
