// Code generated by ent, DO NOT EDIT.

package fee

import (
	"entgo.io/ent"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the fee type in the database.
	Label = "fee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCoinTypeID holds the string denoting the coin_type_id field in the database.
	FieldCoinTypeID = "coin_type_id"
	// FieldFeeCoinTypeID holds the string denoting the fee_coin_type_id field in the database.
	FieldFeeCoinTypeID = "fee_coin_type_id"
	// FieldWithdrawFeeByStableUsd holds the string denoting the withdraw_fee_by_stable_usd field in the database.
	FieldWithdrawFeeByStableUsd = "withdraw_fee_by_stable_usd"
	// FieldWithdrawFeeAmount holds the string denoting the withdraw_fee_amount field in the database.
	FieldWithdrawFeeAmount = "withdraw_fee_amount"
	// FieldCollectFeeAmount holds the string denoting the collect_fee_amount field in the database.
	FieldCollectFeeAmount = "collect_fee_amount"
	// FieldHotWalletFeeAmount holds the string denoting the hot_wallet_fee_amount field in the database.
	FieldHotWalletFeeAmount = "hot_wallet_fee_amount"
	// FieldLowFeeAmount holds the string denoting the low_fee_amount field in the database.
	FieldLowFeeAmount = "low_fee_amount"
	// Table holds the table name of the fee in the database.
	Table = "fees"
)

// Columns holds all SQL columns for fee fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCoinTypeID,
	FieldFeeCoinTypeID,
	FieldWithdrawFeeByStableUsd,
	FieldWithdrawFeeAmount,
	FieldCollectFeeAmount,
	FieldHotWalletFeeAmount,
	FieldLowFeeAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/chain-manager/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultCoinTypeID holds the default value on creation for the "coin_type_id" field.
	DefaultCoinTypeID func() uuid.UUID
	// DefaultFeeCoinTypeID holds the default value on creation for the "fee_coin_type_id" field.
	DefaultFeeCoinTypeID func() uuid.UUID
	// DefaultWithdrawFeeByStableUsd holds the default value on creation for the "withdraw_fee_by_stable_usd" field.
	DefaultWithdrawFeeByStableUsd bool
	// DefaultWithdrawFeeAmount holds the default value on creation for the "withdraw_fee_amount" field.
	DefaultWithdrawFeeAmount decimal.Decimal
	// DefaultCollectFeeAmount holds the default value on creation for the "collect_fee_amount" field.
	DefaultCollectFeeAmount decimal.Decimal
	// DefaultHotWalletFeeAmount holds the default value on creation for the "hot_wallet_fee_amount" field.
	DefaultHotWalletFeeAmount decimal.Decimal
	// DefaultLowFeeAmount holds the default value on creation for the "low_fee_amount" field.
	DefaultLowFeeAmount decimal.Decimal
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
