// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppCoin is the predicate function for appcoin builders.
type AppCoin func(*sql.Selector)

// CoinBase is the predicate function for coinbase builders.
type CoinBase func(*sql.Selector)

// CoinExtra is the predicate function for coinextra builders.
type CoinExtra func(*sql.Selector)

// ExchangeRate is the predicate function for exchangerate builders.
type ExchangeRate func(*sql.Selector)

// Fee is the predicate function for fee builders.
type Fee func(*sql.Selector)

// Tran is the predicate function for tran builders.
type Tran func(*sql.Selector)
